/**
 * Election 2028 — Cabinet & Transition data
 * Real political figures as cabinet options across twelve posts. Stats are
 * game balance, not scholarship; "concerns" are opposition attack lines and
 * reported criticisms as they would surface at a confirmation hearing.
 * One person can hold one job — hire Pompeo at State and he's off the CIA list.
 */
window.CabinetData = {

    GROUPS: [
        { id: 'big4',     title: 'THE BIG FOUR' },
        { id: 'security', title: 'THE SECURITY TEAM' },
        { id: 'domestic', title: 'THE DOMESTIC AGENDA' },
        { id: 'westwing', title: 'THE WEST WING' },
    ],

    POSTS: [
        { id: 'state',    group: 'big4',     title: 'Secretary of State',         icon: '🌍', confirmable: true,  desc: 'The face of American diplomacy. A strong pick steadies every foreign crisis of your term.' },
        { id: 'treasury', group: 'big4',     title: 'Secretary of the Treasury',  icon: '💵', confirmable: true,  desc: 'Steers the economy. Markets price this pick before you finish the announcement.' },
        { id: 'defense',  group: 'big4',     title: 'Secretary of Defense',       icon: '🎖️', confirmable: true,  desc: 'Runs the Pentagon. The Senate scrutinizes this chair hardest.' },
        { id: 'justice',  group: 'big4',     title: 'Attorney General',           icon: '⚖️', confirmable: true,  desc: 'The nation\'s top law officer — and its most politically radioactive chair.' },
        { id: 'homeland', group: 'security', title: 'Secretary of Homeland Security', icon: '🛂', confirmable: true, desc: 'The border, disasters, and everything that goes bump at 3 a.m.' },
        { id: 'cia',      group: 'security', title: 'CIA Director',               icon: '🕵️', confirmable: true,  desc: 'Your eyes in the dark. Competence here shows up in every crisis briefing.' },
        { id: 'un',       group: 'security', title: 'UN Ambassador',              icon: '🕊️', confirmable: true,  desc: 'America\'s voice in the room where the world argues.' },
        { id: 'hhs',      group: 'domestic', title: 'Secretary of Health & Human Services', icon: '🏥', confirmable: true, desc: 'A fifth of the economy and every public-health emergency land on this desk.' },
        { id: 'energy',   group: 'domestic', title: 'Secretary of Energy',        icon: '⚡', confirmable: true,  desc: 'Grid, drilling, renewables — and the nuclear stockpile most people forget it runs.' },
        { id: 'chief',    group: 'westwing', title: 'White House Chief of Staff', icon: '🗂️', confirmable: false, desc: 'Gatekeeper of the Oval. No confirmation needed — loyalty and competence are everything.' },
        { id: 'nsa',      group: 'westwing', title: 'National Security Advisor',  icon: '🧭', confirmable: false, desc: 'The last voice before every hard call. No Senate vote required.' },
        { id: 'press',    group: 'westwing', title: 'Press Secretary',            icon: '🎤', confirmable: false, desc: 'Your voice at the podium every single day.' },
    ],

    OPTIONS: {
        Democrat: {
            state: [
                { id: 'william_burns', name: 'William Burns', age: 72, home: 'Maryland', title: 'Former CIA Director & career diplomat',
                  bio: 'Ambassador to Russia and Jordan, deputy Secretary of State, then CIA Director — the most decorated living American diplomat.',
                  concerns: ['Institutionalist caution may frustrate the base', 'Tied to every establishment consensus of the last 30 years'],
                  competence: 94, loyalty: 62, controversy: 22 },
                { id: 'susan_rice', name: 'Susan Rice', age: 63, home: 'D.C.', title: 'Former National Security Advisor',
                  bio: 'UN Ambassador, National Security Advisor, and domestic policy chief — a three-tool player with scar tissue.',
                  concerns: ['Benghazi-era talking points will be re-litigated on day one', 'Reputation for sharp elbows in the interagency'],
                  competence: 88, loyalty: 76, controversy: 56 },
                { id: 'samantha_power', name: 'Samantha Power', age: 58, home: 'Massachusetts', title: 'Former UN Ambassador & USAID chief',
                  bio: 'Pulitzer-winning human-rights scholar who ran USAID and the UN mission.',
                  concerns: ['Interventionist record alarms restraint wings of both parties', 'Academic paper trail full of quotable lines'],
                  competence: 85, loyalty: 70, controversy: 44 },
                { id: 'chris_coons', name: 'Chris Coons', age: 65, home: 'Delaware', title: 'Senator from Delaware',
                  bio: 'The Senate\'s foreign-relations workhorse and its most-liked member across the aisle.',
                  concerns: ['Taking him costs your party a Senate seat to a special election'],
                  competence: 80, loyalty: 82, controversy: 15 },
                { id: 'wendy_sherman', name: 'Wendy Sherman', age: 79, home: 'Maryland', title: 'Former Deputy Secretary of State',
                  bio: 'Lead negotiator of the Iran nuclear deal and the department\'s former #2.',
                  concerns: ['The Iran deal is a permanent Republican attack line', 'Age will be raised, fairly or not'],
                  competence: 86, loyalty: 68, controversy: 48 },
            ],
            treasury: [
                { id: 'janet_yellen', name: 'Janet Yellen', age: 82, home: 'California', title: 'Former Treasury Secretary & Fed Chair',
                  bio: 'The only person to have led the Fed, the CEA, and Treasury. Markets exhale when she speaks.',
                  concerns: ['Age dominates the coverage', 'Owns the inflation record of the early 2020s'],
                  competence: 94, loyalty: 64, controversy: 26 },
                { id: 'gina_raimondo', name: 'Gina Raimondo', age: 57, home: 'Rhode Island', title: 'Former Commerce Secretary & Governor',
                  bio: 'Venture capitalist turned governor turned Commerce chief — ran the China chips strategy.',
                  concerns: ['The left never forgave her pension reforms', 'Wall Street ties draw progressive fire'],
                  competence: 87, loyalty: 72, controversy: 32 },
                { id: 'elizabeth_warren', name: 'Elizabeth Warren', age: 79, home: 'Massachusetts', title: 'Senator from Massachusetts',
                  bio: 'Built the CFPB, wrote the plans, and terrifies every bank compliance department in America.',
                  concerns: ['Wall Street will fund the opposition campaign personally', 'Costs a Senate seat and a floor of market panic'],
                  competence: 86, loyalty: 55, controversy: 74 },
                { id: 'lael_brainard', name: 'Lael Brainard', age: 66, home: 'D.C.', title: 'Former Fed Vice Chair & NEC Director',
                  bio: 'The quiet technocrat who has run monetary and economic policy from every chair that matters.',
                  concerns: ['Low public profile — no political juice in the pick'],
                  competence: 89, loyalty: 74, controversy: 18 },
                { id: 'jamie_dimon', name: 'Jamie Dimon', age: 72, home: 'New York', title: 'JPMorgan Chase CEO',
                  bio: 'The most powerful banker of his generation, openly restless for a public act.',
                  concerns: ['A Wall Street CEO at Treasury splits your own party', 'Divestment fight would be historic'],
                  competence: 91, loyalty: 40, controversy: 60 },
            ],
            defense: [
                { id: 'michele_flournoy', name: 'Michèle Flournoy', age: 67, home: 'Virginia', title: 'Former Under Secretary of Defense for Policy',
                  bio: 'The Pentagon\'s policy brain across two administrations; the most-prepared SecDef never yet appointed.',
                  concerns: ['Defense-industry consulting ties get a full hearing day'],
                  competence: 91, loyalty: 72, controversy: 26 },
                { id: 'tammy_duckworth', name: 'Tammy Duckworth', age: 60, home: 'Illinois', title: 'Senator & retired Army Lt. Colonel',
                  bio: 'Blackhawk pilot who lost both legs in Iraq, then won a Senate seat. Her story ends arguments.',
                  concerns: ['Costs a Senate seat in a purple-trending state'],
                  competence: 83, loyalty: 80, controversy: 18 },
                { id: 'lloyd_austin', name: 'Lloyd Austin', age: 75, home: 'Georgia', title: 'Former Secretary of Defense',
                  bio: 'Four-star general who already ran the building through two wars.',
                  concerns: ['The undisclosed-hospitalization episode returns', 'Another waiver debate about generals running defense'],
                  competence: 84, loyalty: 76, controversy: 40 },
                { id: 'mark_kelly', name: 'Mark Kelly', age: 64, home: 'Arizona', title: 'Senator, astronaut & Navy combat pilot',
                  bio: 'Flew 39 combat missions and four shuttle flights. Crossover approval most politicians would kill for.',
                  concerns: ['Costs a genuinely at-risk Arizona Senate seat'],
                  competence: 82, loyalty: 78, controversy: 20 },
                { id: 'seth_moulton', name: 'Seth Moulton', age: 49, home: 'Massachusetts', title: 'Congressman & Marine veteran',
                  bio: 'Four tours in Iraq, a decade on Armed Services, and a generational-change pitch.',
                  concerns: ['Thin executive record for the biggest bureaucracy on Earth', 'Made enemies challenging party leadership'],
                  competence: 76, loyalty: 70, controversy: 30 },
            ],
            justice: [
                { id: 'sally_yates', name: 'Sally Yates', age: 68, home: 'Georgia', title: 'Former Acting Attorney General',
                  bio: 'Career prosecutor fired for refusing to defend an order she deemed unlawful. Half the country calls that a résumé.',
                  concerns: ['Her firing is the entire Republican opening statement', 'Seen as a partisan martyr by the right'],
                  competence: 88, loyalty: 72, controversy: 50 },
                { id: 'doug_jones', name: 'Doug Jones', age: 74, home: 'Alabama', title: 'Former Senator from Alabama',
                  bio: 'Prosecuted the Birmingham church bombers, then won a Senate seat in Alabama. Confirmable anywhere.',
                  concerns: ['The base wants a fighter, not a consensus pick'],
                  competence: 82, loyalty: 76, controversy: 16 },
                { id: 'preet_bharara', name: 'Preet Bharara', age: 60, home: 'New York', title: 'Former U.S. Attorney, SDNY',
                  bio: 'The prosecutor who terrified Wall Street and Albany equally, with a media brand to match.',
                  concerns: ['Celebrity-prosecutor profile reads as ambition', 'Fired-by-Trump history makes it a partisan fight'],
                  competence: 85, loyalty: 66, controversy: 46 },
                { id: 'dana_nessel', name: 'Dana Nessel', age: 59, home: 'Michigan', title: 'Michigan Attorney General',
                  bio: 'A brawler who prosecuted fake electors and won statewide twice in a battleground.',
                  concerns: ['Her combative style guarantees a fireworks hearing'],
                  competence: 78, loyalty: 74, controversy: 52 },
                { id: 'merrick_garland', name: 'Merrick Garland', age: 75, home: 'Illinois', title: 'Former Attorney General',
                  bio: 'The institutionalist\'s institutionalist — a judge\'s judge both flanks find maddening.',
                  concerns: ['The left thinks he was too slow; the right thinks he was too political'],
                  competence: 81, loyalty: 60, controversy: 40 },
            ],
            homeland: [
                { id: 'jeh_johnson', name: 'Jeh Johnson', age: 71, home: 'New Jersey', title: 'Former Secretary of Homeland Security',
                  bio: 'Ran DHS through a border surge and the Pentagon\'s legal shop before that. Adult-in-the-room energy.',
                  concerns: ['Corporate law years draw progressive grumbling'],
                  competence: 86, loyalty: 70, controversy: 22 },
                { id: 'alejandro_mayorkas', name: 'Alejandro Mayorkas', age: 68, home: 'D.C.', title: 'Former Secretary of Homeland Security',
                  bio: 'Knows every corridor of the department — and every scar of the job. First secretary impeached since 1876.',
                  concerns: ['His House impeachment is the entire hearing', 'Owns the border numbers of his tenure'],
                  competence: 82, loyalty: 74, controversy: 66 },
                { id: 'val_demings', name: 'Val Demings', age: 71, home: 'Florida', title: 'Former Orlando Police Chief & Congresswoman',
                  bio: 'Career cop who rose to chief, then to Congress and an impeachment-manager turn.',
                  concerns: ['Police-record scrutiny from the left, impeachment grudges from the right'],
                  competence: 79, loyalty: 78, controversy: 34 },
                { id: 'cq_brown', name: 'Charles Q. Brown Jr.', age: 66, home: 'Texas', title: 'Former Chairman of the Joint Chiefs',
                  bio: 'Fighter pilot who ran the entire U.S. military. Discipline for a sprawling department.',
                  concerns: ['Another general in a civilian chair invites a waiver fight'],
                  competence: 87, loyalty: 72, controversy: 28 },
            ],
            cia: [
                { id: 'avril_haines', name: 'Avril Haines', age: 59, home: 'New York', title: 'Former Director of National Intelligence',
                  bio: 'First woman to run the intelligence community; before that, deputy at CIA and the NSC.',
                  concerns: ['Drone-program legal history resurfaces from the left'],
                  competence: 90, loyalty: 74, controversy: 24 },
                { id: 'michael_morell', name: 'Michael Morell', age: 69, home: 'Virginia', title: 'Former Acting CIA Director',
                  bio: 'Twice acting director, briefer of presidents, and the agency\'s favorite explainer of itself.',
                  concerns: ['Signed the Hunter Biden laptop letter — Republicans will read it aloud'],
                  competence: 86, loyalty: 70, controversy: 42 },
                { id: 'sue_gordon', name: 'Sue Gordon', age: 70, home: 'Virginia', title: 'Former Principal Deputy DNI',
                  bio: 'Three decades inside the agency, beloved across parties, forced out and never bitter.',
                  concerns: ['Low public profile means no political cover in a fight'],
                  competence: 88, loyalty: 76, controversy: 14 },
                { id: 'adam_schiff', name: 'Adam Schiff', age: 68, home: 'California', title: 'Senator & former House Intel Chairman',
                  bio: 'Ran House Intelligence and a presidential impeachment. Half the country trusts him completely.',
                  concerns: ['The other half was told for a decade he is the villain', 'Costs a safe Senate seat'],
                  competence: 81, loyalty: 72, controversy: 68 },
            ],
            un: [
                { id: 'linda_thomas_greenfield', name: 'Linda Thomas-Greenfield', age: 76, home: 'Louisiana', title: 'Former UN Ambassador',
                  bio: 'Thirty-five-year foreign service veteran who has already held the chair with distinction.',
                  concerns: ['A safe encore, not a headline'],
                  competence: 86, loyalty: 74, controversy: 14 },
                { id: 'samantha_power', name: 'Samantha Power', age: 58, home: 'Massachusetts', title: 'Former UN Ambassador & USAID chief',
                  bio: 'Knows the building, the veto math, and the speeches that move rooms.',
                  concerns: ['Interventionist record alarms restraint wings of both parties'],
                  competence: 85, loyalty: 70, controversy: 44 },
                { id: 'chris_murphy', name: 'Chris Murphy', age: 55, home: 'Connecticut', title: 'Senator from Connecticut',
                  bio: 'The Senate\'s most fluent foreign-policy communicator of his generation.',
                  concerns: ['Costs a Senate seat for a job the base barely watches'],
                  competence: 80, loyalty: 76, controversy: 20 },
                { id: 'caroline_kennedy', name: 'Caroline Kennedy', age: 70, home: 'New York', title: 'Former Ambassador to Japan & Australia',
                  bio: 'Two ambassadorships, a legendary name, and quiet effectiveness in both.',
                  concerns: ['Dynasty optics; light on multilateral experience'],
                  competence: 76, loyalty: 78, controversy: 18 },
            ],
            hhs: [
                { id: 'vivek_murthy', name: 'Vivek Murthy', age: 51, home: 'Florida', title: 'Former U.S. Surgeon General',
                  bio: 'Twice Surgeon General, the calm clinical voice of two public-health crises.',
                  concerns: ['Gun-violence-as-health-issue stance re-runs his 2014 fight'],
                  competence: 85, loyalty: 78, controversy: 26 },
                { id: 'xavier_becerra', name: 'Xavier Becerra', age: 70, home: 'California', title: 'Former HHS Secretary',
                  bio: 'Ran the department once already and sued his way through a decade of health-policy fights before that.',
                  concerns: ['Not a doctor — the same attack as last time'],
                  competence: 79, loyalty: 74, controversy: 30 },
                { id: 'michelle_lujan_grisham', name: 'Michelle Lujan Grisham', age: 69, home: 'New Mexico', title: 'Former Governor of New Mexico',
                  bio: 'Former state health secretary turned governor — executive experience on exactly this portfolio.',
                  concerns: ['A settled staff lawsuit from 2019 resurfaces every cycle'],
                  competence: 78, loyalty: 72, controversy: 36 },
                { id: 'ashish_jha', name: 'Ashish Jha', age: 57, home: 'Rhode Island', title: 'Former White House COVID Response Coordinator',
                  bio: 'The dean who became the country\'s pandemic explainer-in-chief.',
                  concerns: ['COVID-era decisions get a full partisan autopsy'],
                  competence: 84, loyalty: 74, controversy: 32 },
            ],
            energy: [
                { id: 'jennifer_granholm', name: 'Jennifer Granholm', age: 69, home: 'Michigan', title: 'Former Energy Secretary & Governor',
                  bio: 'Two-term governor who already ran the department through the biggest energy bill in history.',
                  concerns: ['Stock-disclosure stumbles from her first tour return'],
                  competence: 83, loyalty: 74, controversy: 30 },
                { id: 'jay_inslee', name: 'Jay Inslee', age: 77, home: 'Washington', title: 'Former Governor of Washington',
                  bio: 'Ran for president on climate alone, then governed like he meant it.',
                  concerns: ['Fossil-state senators treat him as a declaration of war'],
                  competence: 80, loyalty: 76, controversy: 42 },
                { id: 'ernest_moniz', name: 'Ernest Moniz', age: 83, home: 'Massachusetts', title: 'Former Energy Secretary & MIT physicist',
                  bio: 'The physicist who negotiated the technical half of the Iran deal.',
                  concerns: ['Age; and the Iran deal never stops being an attack line'],
                  competence: 88, loyalty: 68, controversy: 34 },
                { id: 'john_podesta', name: 'John Podesta', age: 79, home: 'D.C.', title: 'Former senior climate advisor',
                  bio: 'Ran climate policy for three presidents and a White House for one.',
                  concerns: ['Decades of hacked-email lore make him a right-wing folk villain'],
                  competence: 82, loyalty: 78, controversy: 46 },
            ],
            chief: [
                { id: 'jeff_zients', name: 'Jeff Zients', age: 61, home: 'D.C.', title: 'Former White House Chief of Staff',
                  bio: 'The fix-it man — healthcare.gov rescue, COVID response, then the chief\'s office itself.',
                  concerns: [], competence: 88, loyalty: 82, controversy: 0 },
                { id: 'jen_omalley', name: 'Jen O\'Malley Dillon', age: 52, home: 'Massachusetts', title: 'Campaign manager',
                  bio: 'Ran your war room. Total loyalty, campaign-honed instincts, no learning curve.',
                  concerns: [], competence: 84, loyalty: 92, controversy: 0 },
                { id: 'mitch_landrieu', name: 'Mitch Landrieu', age: 68, home: 'Louisiana', title: 'Former New Orleans Mayor',
                  bio: 'Executive operator with a southern touch and an infrastructure-czar tour.',
                  concerns: [], competence: 80, loyalty: 80, controversy: 0 },
                { id: 'ron_klain', name: 'Ron Klain', age: 67, home: 'D.C.', title: 'Former White House Chief of Staff',
                  bio: 'Has literally done the job; knows where every lever in the building is.',
                  concerns: [], competence: 90, loyalty: 84, controversy: 0 },
            ],
            nsa: [
                { id: 'jake_sullivan', name: 'Jake Sullivan', age: 51, home: 'Minnesota', title: 'Former National Security Advisor',
                  bio: 'The youngest NSA in a generation, tempered by four years of the hardest file.',
                  concerns: [], competence: 89, loyalty: 80, controversy: 0 },
                { id: 'colin_kahl', name: 'Colin Kahl', age: 57, home: 'California', title: 'Former Under Secretary of Defense for Policy',
                  bio: 'Pentagon policy chief and vice-presidential national security hand.',
                  concerns: [], competence: 83, loyalty: 78, controversy: 0 },
                { id: 'wendy_sherman', name: 'Wendy Sherman', age: 79, home: 'Maryland', title: 'Former Deputy Secretary of State',
                  bio: 'Iron negotiator with every backchannel number saved.',
                  concerns: [], competence: 86, loyalty: 70, controversy: 0 },
            ],
            press: [
                { id: 'jen_psaki', name: 'Jen Psaki', age: 50, home: 'Connecticut', title: 'Former Press Secretary',
                  bio: 'Circle-backs and all — the most effective podium presence of her era.',
                  concerns: [], competence: 88, loyalty: 80, controversy: 0 },
                { id: 'karine_jean_pierre', name: 'Karine Jean-Pierre', age: 54, home: 'New York', title: 'Former Press Secretary',
                  bio: 'Historic, disciplined, unrattled under fire.',
                  concerns: [], competence: 76, loyalty: 84, controversy: 0 },
                { id: 'symone_sanders', name: 'Symone Sanders', age: 39, home: 'Nebraska', title: 'Strategist & broadcaster',
                  bio: 'Fast, fearless, made for the cable-news knife fight.',
                  concerns: [], competence: 80, loyalty: 78, controversy: 0 },
            ],
        },

        Republican: {
            state: [
                { id: 'mike_pompeo', name: 'Mike Pompeo', age: 64, home: 'Kansas', title: 'Former Secretary of State & CIA Director',
                  bio: 'West Point first-in-class who has run both Langley and Foggy Bottom.',
                  concerns: ['Enemies from his first tour line up to testify', 'Own presidential ambitions never quite sleep'],
                  competence: 86, loyalty: 70, controversy: 52 },
                { id: 'nikki_haley', name: 'Nikki Haley', age: 56, home: 'South Carolina', title: 'Former UN Ambassador & Governor',
                  bio: 'Governor, UN Ambassador, presidential contender — the establishment\'s favorite hawk.',
                  concerns: ['Primary-trail attacks on your wing of the party are all on tape', 'Everyone knows she still wants your job'],
                  competence: 86, loyalty: 52, controversy: 44 },
                { id: 'robert_obrien', name: 'Robert O\'Brien', age: 62, home: 'California', title: 'Former National Security Advisor',
                  bio: 'Hostage negotiator turned NSA — presentable, prepared, confirmable.',
                  concerns: ['Light State Department experience for the top chair'],
                  competence: 82, loyalty: 76, controversy: 26 },
                { id: 'bill_hagerty', name: 'Bill Hagerty', age: 69, home: 'Tennessee', title: 'Senator & former Ambassador to Japan',
                  bio: 'Private-equity discipline plus a Tokyo ambassadorship. The Senate confirms its own.',
                  concerns: ['Costs a Senate seat, albeit a safe one'],
                  competence: 79, loyalty: 80, controversy: 18 },
                { id: 'ric_grenell', name: 'Ric Grenell', age: 62, home: 'California', title: 'Former Acting DNI & Ambassador to Germany',
                  bio: 'The brawler-diplomat: Berlin, the Balkans file, and acting DNI, all played at full volume.',
                  concerns: ['European allies openly dread the pick', 'A hearing built entirely of his own tweets'],
                  competence: 74, loyalty: 84, controversy: 62 },
            ],
            treasury: [
                { id: 'scott_bessent', name: 'Scott Bessent', age: 66, home: 'South Carolina', title: 'Former Treasury Secretary & hedge fund manager',
                  bio: 'Soros\' old chief investor turned Republican Treasury chief — markets know his voice.',
                  concerns: ['Hedge-fund history cuts both directions politically'],
                  competence: 85, loyalty: 74, controversy: 32 },
                { id: 'glenn_youngkin', name: 'Glenn Youngkin', age: 61, home: 'Virginia', title: 'Former Governor & Carlyle co-CEO',
                  bio: 'Ran a $250B fund, then a purple state. Fleece-vest fluency in both languages.',
                  concerns: ['Presidential ambitions make him a rival inside the building'],
                  competence: 84, loyalty: 66, controversy: 26 },
                { id: 'kevin_hassett', name: 'Kevin Hassett', age: 66, home: 'D.C.', title: 'Former CEA Chairman & NEC Director',
                  bio: 'The supply-side economist who has staffed every Republican economic debate since 2000.',
                  concerns: ['"Dow 36,000" follows him into every hearing room'],
                  competence: 78, loyalty: 82, controversy: 28 },
                { id: 'larry_kudlow', name: 'Larry Kudlow', age: 81, home: 'Connecticut', title: 'Former NEC Director & broadcaster',
                  bio: 'Television-fluent supply-sider; the base\'s favorite economics teacher.',
                  concerns: ['Economists wince; age becomes the story'],
                  competence: 72, loyalty: 84, controversy: 42 },
                { id: 'jamie_dimon', name: 'Jamie Dimon', age: 72, home: 'New York', title: 'JPMorgan Chase CEO',
                  bio: 'The most powerful banker of his generation, openly restless for a public act.',
                  concerns: ['Populists call it surrender to Wall Street', 'Divestment fight would be historic'],
                  competence: 91, loyalty: 40, controversy: 58 },
            ],
            defense: [
                { id: 'tom_cotton', name: 'Tom Cotton', age: 51, home: 'Arkansas', title: 'Senator & Army combat veteran',
                  bio: 'Harvard Law to Ranger School to the Senate — the hawk\'s hawk with infantry time in two wars.',
                  concerns: ['Democrats make the hearing a spectacle', 'Send-in-the-troops op-ed never dies'],
                  competence: 83, loyalty: 80, controversy: 54 },
                { id: 'mike_waltz', name: 'Mike Waltz', age: 54, home: 'Florida', title: 'Former National Security Advisor & Green Beret',
                  bio: 'First Green Beret elected to Congress, then the NSC corner office.',
                  concerns: ['The group-chat episode gets its own hearing day'],
                  competence: 80, loyalty: 76, controversy: 40 },
                { id: 'joni_ernst', name: 'Joni Ernst', age: 58, home: 'Iowa', title: 'Senator & retired Army Lt. Colonel',
                  bio: 'First female combat veteran in the Senate; Armed Services fixture.',
                  concerns: ['Costs an Iowa Senate seat'],
                  competence: 79, loyalty: 72, controversy: 24 },
                { id: 'elbridge_colby', name: 'Elbridge Colby', age: 49, home: 'D.C.', title: 'Former Under Secretary of Defense for Policy',
                  bio: 'The China-first strategist whose defense doctrine both parties quietly borrowed.',
                  concerns: ['Europe hawks fight the Asia-first pivot on the record'],
                  competence: 82, loyalty: 74, controversy: 36 },
                { id: 'pete_hegseth', name: 'Pete Hegseth', age: 48, home: 'Tennessee', title: 'Former Defense Secretary & Army veteran',
                  bio: 'Two Bronze Stars, a cable-news decade, and one turbulent Pentagon tour.',
                  concerns: ['Personal-conduct allegations from his first confirmation return', 'Management record at the building is the case against'],
                  competence: 66, loyalty: 86, controversy: 80 },
            ],
            justice: [
                { id: 'john_ratcliffe', name: 'John Ratcliffe', age: 63, home: 'Texas', title: 'Former CIA Director & DNI',
                  bio: 'Federal prosecutor who went on to run both DNI and CIA.',
                  concerns: ['Resume-inflation flap from 2019 is opposition exhibit A'],
                  competence: 77, loyalty: 82, controversy: 46 },
                { id: 'pam_bondi', name: 'Pam Bondi', age: 63, home: 'Florida', title: 'Former U.S. & Florida Attorney General',
                  bio: 'Eighteen years a prosecutor, Florida AG, then the main chair at Justice.',
                  concerns: ['Loyalty-over-independence is the entire Democratic case'],
                  competence: 75, loyalty: 84, controversy: 52 },
                { id: 'ted_cruz', name: 'Ted Cruz', age: 57, home: 'Texas', title: 'Senator & former Texas Solicitor General',
                  bio: 'Nine Supreme Court arguments before 40; the sharpest legal mind his enemies ever hated.',
                  concerns: ['Every senator has a personal Ted Cruz story', 'Costs a Senate seat and a news cycle of glee'],
                  competence: 84, loyalty: 62, controversy: 64 },
                { id: 'andrew_bailey', name: 'Andrew Bailey', age: 47, home: 'Missouri', title: 'Missouri Attorney General',
                  bio: 'Combat veteran with a culture-war docket and a young man\'s energy.',
                  concerns: ['Thin federal experience; loud litigation record'],
                  competence: 72, loyalty: 80, controversy: 46 },
                { id: 'ken_paxton', name: 'Ken Paxton', age: 65, home: 'Texas', title: 'Texas Attorney General',
                  bio: 'The most-investigated AG in America — and the most-beloved by the base for exactly that.',
                  concerns: ['Impeached by his own party\'s statehouse', 'Whistleblower settlements and securities charges fill the binder'],
                  competence: 68, loyalty: 78, controversy: 88 },
            ],
            homeland: [
                { id: 'kristi_noem', name: 'Kristi Noem', age: 56, home: 'South Dakota', title: 'Former DHS Secretary & Governor',
                  bio: 'Two-term governor who has already run the department.',
                  concerns: ['The book excerpt about the dog never, ever goes away'],
                  competence: 74, loyalty: 84, controversy: 54 },
                { id: 'tom_homan', name: 'Tom Homan', age: 66, home: 'New York', title: 'Former border czar & acting ICE Director',
                  bio: 'Thirty years from Border Patrol agent to the border czar\'s office.',
                  concerns: ['Family-separation testimony is the hearing\'s centerpiece'],
                  competence: 78, loyalty: 86, controversy: 68 },
                { id: 'chad_wolf', name: 'Chad Wolf', age: 52, home: 'Texas', title: 'Former Acting DHS Secretary',
                  bio: 'Ran the department in an acting capacity through a turbulent year.',
                  concerns: ['GAO found his original appointment itself invalid'],
                  competence: 72, loyalty: 80, controversy: 48 },
                { id: 'mark_green', name: 'Mark Green', age: 64, home: 'Tennessee', title: 'Former House Homeland Security Chairman',
                  bio: 'Army flight surgeon on the Bin Laden mission, then the House\'s homeland chair.',
                  concerns: ['Old comments on vaccines and culture-war files resurface'],
                  competence: 76, loyalty: 78, controversy: 38 },
            ],
            cia: [
                { id: 'john_ratcliffe', name: 'John Ratcliffe', age: 63, home: 'Texas', title: 'Former CIA Director & DNI',
                  bio: 'Has already held the chair; the workforce knows him.',
                  concerns: ['Politicization-of-intel charge follows every appearance'],
                  competence: 78, loyalty: 82, controversy: 44 },
                { id: 'devin_nunes', name: 'Devin Nunes', age: 55, home: 'California', title: 'Former House Intelligence Chairman',
                  bio: 'Ran House Intel through its most partisan decade.',
                  concerns: ['Democrats consider the pick a declaration of war', 'Media-lawsuit history fills a hearing day'],
                  competence: 68, loyalty: 88, controversy: 72 },
                { id: 'kash_patel', name: 'Kash Patel', age: 48, home: 'Nevada', title: 'Former FBI Director',
                  bio: 'Prosecutor, NSC staffer, FBI chief — the movement\'s favorite institutional disruptor.',
                  concerns: ['His enemies-list rhetoric is quoted back verbatim', 'Half the Senate considers him disqualifying on principle'],
                  competence: 64, loyalty: 92, controversy: 84 },
                { id: 'robert_obrien', name: 'Robert O\'Brien', age: 62, home: 'California', title: 'Former National Security Advisor',
                  bio: 'Steady hand with NSC command of the intel product.',
                  concerns: ['Never served inside the agency he\'d run'],
                  competence: 80, loyalty: 76, controversy: 26 },
            ],
            un: [
                { id: 'nikki_haley', name: 'Nikki Haley', age: 56, home: 'South Carolina', title: 'Former UN Ambassador & Governor',
                  bio: 'Owned the chamber once already; allies remember.',
                  concerns: ['Everyone knows she still wants your job'],
                  competence: 87, loyalty: 52, controversy: 40 },
                { id: 'elise_stefanik', name: 'Elise Stefanik', age: 44, home: 'New York', title: 'House Republican Conference Chair',
                  bio: 'The conference chair whose university-president hearings went viral worldwide.',
                  concerns: ['A House seat and leadership fight follow her out the door'],
                  competence: 76, loyalty: 84, controversy: 42 },
                { id: 'kelly_craft', name: 'Kelly Craft', age: 66, home: 'Kentucky', title: 'Former UN Ambassador',
                  bio: 'Held the chair before; donor-class polish, no drama.',
                  concerns: ['Attendance record from her Canada posting returns'],
                  competence: 72, loyalty: 78, controversy: 26 },
                { id: 'ric_grenell', name: 'Ric Grenell', age: 62, home: 'California', title: 'Former Acting DNI & Ambassador to Germany',
                  bio: 'The volume knob only goes up. Adversaries take him seriously.',
                  concerns: ['A hearing built entirely of his own tweets'],
                  competence: 74, loyalty: 84, controversy: 60 },
            ],
            hhs: [
                { id: 'marty_makary', name: 'Marty Makary', age: 58, home: 'Maryland', title: 'Former FDA Commissioner & Johns Hopkins surgeon',
                  bio: 'Surgeon-author who ran the FDA with a reformer\'s zeal.',
                  concerns: ['COVID-era contrarian takes get replayed at the hearing'],
                  competence: 82, loyalty: 74, controversy: 36 },
                { id: 'bobby_jindal', name: 'Bobby Jindal', age: 57, home: 'Louisiana', title: 'Former Governor & HHS Assistant Secretary',
                  bio: 'Ran Louisiana\'s health department at 24 and the state at 36 — the wonk\'s wonk.',
                  concerns: ['His governorship ended deeply unpopular at home'],
                  competence: 81, loyalty: 72, controversy: 30 },
                { id: 'rfk_jr', name: 'Robert F. Kennedy Jr.', age: 74, home: 'California', title: 'Former HHS Secretary',
                  bio: 'The most famous dissident in American public health, with a movement behind him.',
                  concerns: ['Vaccine-skepticism record makes medical groups unanimous in opposition', 'Every past statement is a hearing exhibit'],
                  competence: 62, loyalty: 70, controversy: 86 },
                { id: 'ben_carson', name: 'Ben Carson', age: 76, home: 'Florida', title: 'Former HUD Secretary & neurosurgeon',
                  bio: 'Legendary pediatric neurosurgeon with a cabinet tour already behind him.',
                  concerns: ['HUD furniture flap and low-energy management rap return'],
                  competence: 74, loyalty: 78, controversy: 28 },
            ],
            energy: [
                { id: 'chris_wright', name: 'Chris Wright', age: 63, home: 'Colorado', title: 'Former Energy Secretary & Liberty Energy CEO',
                  bio: 'Fracking pioneer who has run the department and the drill sites.',
                  concerns: ['Climate-dismissal quotes headline the opposition file'],
                  competence: 80, loyalty: 80, controversy: 42 },
                { id: 'doug_burgum', name: 'Doug Burgum', age: 72, home: 'North Dakota', title: 'Former Interior Secretary & Governor',
                  bio: 'Software-billionaire governor who ran Interior and the energy council.',
                  concerns: ['Oil-executive dinner fundraising stories resurface'],
                  competence: 83, loyalty: 76, controversy: 28 },
                { id: 'rick_perry', name: 'Rick Perry', age: 78, home: 'Texas', title: 'Former Energy Secretary & Governor',
                  bio: 'Famously wanted to abolish the department, then ran it and liked it.',
                  concerns: ['"Oops" plays before every hearing clip package'],
                  competence: 72, loyalty: 78, controversy: 34 },
                { id: 'dan_brouillette', name: 'Dan Brouillette', age: 66, home: 'Louisiana', title: 'Former Energy Secretary',
                  bio: 'The low-drama professional who already ran the building.',
                  concerns: ['Zero political sizzle in the pick'],
                  competence: 78, loyalty: 76, controversy: 16 },
            ],
            chief: [
                { id: 'susie_wiles', name: 'Susie Wiles', age: 71, home: 'Florida', title: 'Former White House Chief of Staff',
                  bio: 'The Ice Maiden — runs a tight building and never leaks.',
                  concerns: [], competence: 88, loyalty: 86, controversy: 0 },
                { id: 'chris_lacivita', name: 'Chris LaCivita', age: 62, home: 'Virginia', title: 'Campaign strategist',
                  bio: 'Knife-fighter who ran your ground war. The staff will fear him. Good.',
                  concerns: [], competence: 80, loyalty: 84, controversy: 0 },
                { id: 'kevin_mccarthy', name: 'Kevin McCarthy', age: 63, home: 'California', title: 'Former Speaker of the House',
                  bio: 'Knows every member, every district, and every favor owed on the Hill.',
                  concerns: [], competence: 78, loyalty: 66, controversy: 0 },
                { id: 'reince_priebus', name: 'Reince Priebus', age: 56, home: 'Wisconsin', title: 'Former RNC Chairman & Chief of Staff',
                  bio: 'Party-establishment glue with a previous (brief) tour in the chair.',
                  concerns: [], competence: 74, loyalty: 68, controversy: 0 },
            ],
            nsa: [
                { id: 'robert_obrien', name: 'Robert O\'Brien', age: 62, home: 'California', title: 'Former National Security Advisor',
                  bio: 'Has held the chair; the process runs clean under him.',
                  concerns: [], competence: 82, loyalty: 78, controversy: 0 },
                { id: 'keith_kellogg', name: 'Keith Kellogg', age: 84, home: 'Virginia', title: 'Retired Lt. General & special envoy',
                  bio: 'Three-star with NSC chief-of-staff tours and envoy scar tissue.',
                  concerns: [], competence: 76, loyalty: 82, controversy: 0 },
                { id: 'hr_mcmaster', name: 'H.R. McMaster', age: 66, home: 'Pennsylvania', title: 'Former National Security Advisor',
                  bio: 'Warrior-scholar who wrote the book on speaking truth to power — literally.',
                  concerns: [], competence: 88, loyalty: 60, controversy: 0 },
            ],
            press: [
                { id: 'karoline_leavitt', name: 'Karoline Leavitt', age: 31, home: 'New Hampshire', title: 'Former Press Secretary',
                  bio: 'Youngest ever at the podium and never rattled.',
                  concerns: [], competence: 80, loyalty: 88, controversy: 0 },
                { id: 'kayleigh_mcenany', name: 'Kayleigh McEnany', age: 40, home: 'Florida', title: 'Former Press Secretary',
                  bio: 'Binder always loaded; cable-ready every hour of the day.',
                  concerns: [], competence: 78, loyalty: 82, controversy: 0 },
                { id: 'sarah_huckabee', name: 'Sarah Huckabee Sanders', age: 46, home: 'Arkansas', title: 'Governor & former Press Secretary',
                  bio: 'Held the podium through the stormiest briefings of the era, then won a governorship.',
                  concerns: [], competence: 76, loyalty: 84, controversy: 0 },
            ],
        },
    },
};
