const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');
const raw=fs.readFileSync(path.join(root,'data/natural-earth-110m.geojson'),'utf8');
const project=([lon,lat])=>[(lon+180)/3.6,(85-lat)/3.6].map(v=>Number(v.toFixed(3)));
const features=JSON.parse(raw).features.filter(f=>f.properties.ADM0_A3!=='ATA').map(f=>{
  const p=f.properties;
  const polygons=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;
  const d=polygons.flatMap(poly=>poly.map(ring=>'M'+ring.map(point=>project(point).join(',')).join('L')+'Z')).join('');
  const [x,y]=project([p.LABEL_X,p.LABEL_Y]);
  return {id:p.ADM0_A3,name:p.NAME_LONG,x,y,d,population:p.POP_EST,populationYear:p.POP_YEAR};
});
fs.writeFileSync(path.join(root,'js/world-geometry.js'),'// Generated by scripts/compile-world.cjs. Natural Earth public-domain geometry.\nwindow.WorldGeometry='+JSON.stringify({sha256:crypto.createHash('sha256').update(raw).digest('hex'),projection:'Equirectangular; 85N to 65S',features})+';\n');
console.log(`Compiled ${features.length} countries with one shared projection.`);
